dataset = https://www.kaggle.com/datasets/sobhanmoosavi/us-accidents

## US ACCIDENTS EXPLORATORY DATA ANALYSIS

## dataset consisting of 7728394 rows Ã— 45 columns

#TODO - TALK ABOUT EDA

#TODO - TALK ABOUT THE DATASET (SOURCE, What it contains, how it will be useful)

#kaggle 


#information about accidents 


#can use useful to prevent accidents

# Download the Data

In [1]:
import pandas as pd  

# Define all columns needed
columns_needed = [
    "ID", "Severity", "Start_Time", "End_Time", "Start_Lat", "Start_Lng",
    "End_Lat", "End_Lng", "Distance(mi)", "Description", "Street", "City",
    "County", "State", "Zipcode", "Country", "Timezone", "Airport_Code",
    "Weather_Timestamp", "Temperature(F)", "Wind_Chill(F)", "Humidity(%)",
    "Pressure(in)", "Visibility(mi)", "Wind_Direction", "Wind_Speed(mph)",
    "Precipitation(in)", "Weather_Condition", "Amenity", "Bump", "Crossing",
    "Give_Way", "Junction", "No_Exit", "Railway", "Roundabout", "Station",
    "Stop", "Traffic_Calming", "Traffic_Signal", "Turning_Loop", "Sunrise_Sunset",
    "Civil_Twilight", "Nautical_Twilight", "Astronomical_Twilight"
]

# Optimize data types
dtypes = {
    "ID": "string",
    "Severity": "int8",
    "Start_Lat": "float32",
    "Start_Lng": "float32",
    "End_Lat": "float32",
    "End_Lng": "float32",
    "Distance(mi)": "float32",
    "State": "category",
    "Zipcode": "string",
    "Country": "category",
    "Timezone": "category",
    "Airport_Code": "category",
    "Temperature(F)": "float32",
    "Wind_Chill(F)": "float32",
    "Humidity(%)": "float32",
    "Pressure(in)": "float32",
    "Visibility(mi)": "float32",
    "Wind_Speed(mph)": "float32",
    "Precipitation(in)": "float32",
    "Weather_Condition": "category",
    "Amenity": "bool",
    "Bump": "bool",
    "Crossing": "bool",
    "Give_Way": "bool",
    "Junction": "bool",
    "No_Exit": "bool",
    "Railway": "bool",
    "Roundabout": "bool",
    "Station": "bool",
    "Stop": "bool",
    "Traffic_Calming": "bool",
    "Traffic_Signal": "bool",
    "Turning_Loop": "bool",
    "Sunrise_Sunset": "category",
    "Civil_Twilight": "category",
    "Nautical_Twilight": "category",
    "Astronomical_Twilight": "category"
}

# Read in chunks
chunk_size = 100000  

df_list = []
for chunk in pd.read_csv("US_Accidents_March23.csv", usecols=columns_needed, 
                         dtype=dtypes, parse_dates=["Start_Time", "End_Time", "Weather_Timestamp"],
                         chunksize=chunk_size, on_bad_lines='skip', low_memory=True):
    df_list.append(chunk)

# Combine all chunks
df = pd.concat(df_list, ignore_index=True)

# Memory usage check
print(df.info(memory_usage="deep"))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 45 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     string
 1   Severity               int8
 2   Start_Time             object
 3   End_Time               object
 4   Start_Lat              float32
 5   Start_Lng              float32
 6   End_Lat                float32
 7   End_Lng                float32
 8   Distance(mi)           float32
 9   Description            object
 10  Street                 object
 11  City                   object
 12  County                 object
 13  State                  object
 14  Zipcode                string
 15  Country                category
 16  Timezone               object
 17  Airport_Code           object
 18  Weather_Timestamp      datetime64[ns]
 19  Temperature(F)         float32
 20  Wind_Chill(F)          float32
 21  Humidity(%)            float32
 22  Pressure(in)           float32
 23  Visibility(mi)         float32
 24  Wind_Direction         object
 25  Wind_Speed(mph)        float32
 26  Precipitation(in)      float32
 27  Weather_Condition      object
 28  Amenity                bool
 29  Bump                   bool
 30  Crossing               bool
 31  Give_Way               bool
 32  Junction               bool
 33  No_Exit                bool
 34  Railway                bool
 35  Roundabout             bool
 36  Station                bool
 37  Stop                   bool
 38  Traffic_Calming        bool
 39  Traffic_Signal         bool
 40  Turning_Loop           bool
 41  Sunrise_Sunset         category
 42  Civil_Twilight         category
 43  Nautical_Twilight      category
 44  Astronomical_Twilight  category
dtypes: bool(13), category(5), datetime64[ns](1), float32(12), int8(1), object(11), string(2)
memory usage: 7.6 GB
None

## Importing Libraries & Data

In [8]:
#libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

#save
df.to_csv("cleaned_US_Accidents.csv", index=False)

## Data Preparation and Cleaning

1. Look at some of the information about the data & columns

2. fix any missing or incorrect values

In [7]:
df

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.010,Right lane blocked due to accident on I-70 Eas...,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.010,Accident on Brice Rd at Tussing Rd. Expect del...,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.010,Accident on OH-32 State Route 32 Westbound at ...,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.010,Accident on I-75 Southbound at Exits 52 52B US...,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.010,Accident on McEwen Rd at OH-725 Miamisburg Cen...,...,False,False,False,False,True,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7728389,A-7777757,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.002480,-117.379356,33.998878,-117.370941,0.543,At Market St - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
7728390,A-7777758,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.766960,-117.148064,32.765549,-117.153633,0.338,At Camino Del Rio/Mission Center Rd - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
7728391,A-7777759,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.775452,-117.847794,33.777401,-117.857269,0.561,At Glassell St/Grand Ave - Accident. in the ri...,...,False,False,False,False,False,False,Day,Day,Day,Day
7728392,A-7777760,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.992458,-118.403023,33.983109,-118.395653,0.772,At CA-90/Marina Fwy/Jefferson Blvd - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
7728393,A-7777761,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.133930,-117.230919,34.137360,-117.239342,0.537,At Highland Ave/Arden Ave - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day